### PR TITLE
Issue 309

### LINKED ISSUE #309: cannot read string attribute with array size 1
Hi,

I've encountered a problem that the h5cpp (v0.0.7) is no able to read string attribute which has array size 1. But if the array size shows as scalar, it works. 

>HDF5-DIAG: Error detected in HDF5 (1.10.0-patch1) thread 140552714533760:
  #000: ../../../src/H5A.c line 695 in H5Aread(): unable to read attribute
    major: Attribute
    minor: Read failed
  #001: ../../../src/H5Aint.c line 544 in H5A__read(): datatype conversion failed
    major: Attribute
    minor: Unable to encode value
  #002: ../../../src/H5T.c line 4844 in H5T_convert(): data type conversion failed
    major: Attribute
    minor: Unable to encode value
  #003: ../../../src/H5Tconv.c line 3193 in H5T__conv_vlen(): unable to convert between src and dest datatypes
    major: Datatype
    minor: Feature is unsupported
  #004: ../../../src/H5T.c line 4560 in H5T_path_find(): no appropriate function for conversion path
    major: Datatype
    minor: Unable to initialize object
terminate called after throwing an instance of 'std::runtime_error'

```C++
std::string base_class;
file.root().attributes["NX_class"].read(base_class); //works, the array size is scalar
std::cout<<base_class<<std::endl;

std::string testattr; 
file.root().attributes["testattr"].read(testattr); // doesn't work, the array size is 1
std::cout<<testattr<<std::endl;
```
testfile

### PR DESCRIPTION
**Pull request by jkotan**
It resolves #309.

It adds only the tests  which some of them fails because of bug. 

Comparing to  #315 I add also `test_int_overflow` which is also fixed by #316. A similar problem (but with fields) was notices in #313, i.e. when you read a big value you loose informations.

### CODE REVIEW

**Comment by martukas** [comment]
Add tickets to upcoming milestone whenever appropriate.

**Comment by martukas** [comment]
Why is this ("cannot read string attribute with array size 1") reference the issue with integer signedness? Did that ticket need to be reopened?

**Comment by jkotan** [comment]
It fixed #309 but it is also related to the problem @yuelongyu  presents in #313 (how to get (un)signed from datatype) with the field but with attributes (`test_int_overflow`).

**Comment by jkotan** [comment]
after adding the fix the tests:

[  FAILED  ] 4 tests, listed below:
[  FAILED  ] AttributeScalarIO.test_int_overflow
[  FAILED  ] AttributeFixedStringIO.simple_read
[  FAILED  ] AttributeFixedStringIO.scalar_read
[  FAILED  ] AttributeFixedStringIO.simple_vector_read

no more fails.

**Comment by jkotan** [comment]
It looks like the test are not automatically re-triggered.

**Comment by martukas** [comment]
Hmm, not sure why that is. Please also merge from master, as I have updated some Jenkins-related stuff. It should build faster as there are fewer platforms tested now.
I don't think you have accounts to log into the Jenkins server, but you could try. Unfortunately, most of the office is out on holidays because of midsommar here, so I may not be able to do much about it right now...

**Comment by jkotan** [comment]
It would not surprised me if the similar fix could help with #260.

**Comment by martukas** [comment]
I see the tests are nice now. But I still need to think about this. I don't think providing a null datatype is the right solution in the long run. We need a more surgical approach that fixes the problem for string I/O only, and not enforce reading of data in this way by default. I know where you are coming from. I am also always totally in favor of more simple, more user-friendly, more obvious interfaces. But in this case we really need to balance it with providing an honest wrapper to the HDF5 API and not suppress some of its features simply because we don't personally need them.

**Comment by jkotan** [comment]
Since problems with the string are the most annoying I've just decided to limit the fix to STRING type. Maybe we can put if in the next release. 

For me it is better to keep the fix in the `read` method with one parameter.  And if someone else would have crazy idea to execute `H5Fread` command with weird `mem_type` of output buffer (as it is implemented in `master` now) he/she can still use the `read` method with two parameters.

**Comment by jkotan** [comment]
BTW, @martukas, https://github.com/ess-dmsc/h5cpp/blob/ff48f596a67caaafe9f66b755b75473343426f35/src/h5cpp/attribute/attribute.hpp#L363
is not costructor of `datatype` by call to the member function of `Attribute` which fetch the file_type. So it is neither NULL nor abstract, undefined type.  I think it is better to use it when we have many-to-one relation like in string or bool cases.

**Pull request merged**
