### PR TITLE
HDF compatibility fixes

### LINKED ISSUE #451: Compatibility issues with latest HDF (v. 1.12.0)
I am trying to compile the source but ran into a couple of issues:

1. **H5I_REFERENCE was not declared in this scope** 
Turns out this was removed in HDF 1.10 according to the release notes.

2. **too few arguments to function herr_t H5Oget_info3**
Indeed I see this declared as ```
H5_DLL herr_t H5Oget_info3(hid_t loc_id, H5O_info2_t *oinfo, unsigned fields);```
in my H5Opublic.h

3. **struct H5O_info2_t’ has no member named ‘addr’**
I suspect that is related to this item in the 1.12.0 release notes:
```
      * Introduced new H5Oget_native_info, H5Oget_native_info_by_name and
        H5Oget_native_info_by_idx API calls, along with their associated H5O_native_info_t
        struct, which are used to retrieve the native HDF5 file format-specific information
        about an object. This information (such as object header info and B-tree/heap info)
        has been removed from the new H5O_info2_t struct so that the more generic
        H5Oget_info(_by_name/_by_idx)3 routines will not try to retrieve it for non-native
        VOL connectors.
```
Im am happy to help fixing these things, I would just like to bring up for discussion here how to best go about it.

### PR DESCRIPTION
**Pull request by sekoenig**
My take to fix #451.  Please review in particluar the last commit since it seems to leave the ObjectId class essentially empty...

### CODE REVIEW

**Comment by eugenwintersberger** [comment]
The code looks good for me. However, there are some things we should consider:
* are there any issues with older versions of HDF5 (1.12 is really bleeding edge stuff)
* will ObjectId still serve its purpose?
* how are we identifying an object uniquely in an HDF5 file without its address as the mere path does not work?

Once these questions are solved I happily merge this pull request ;)

**Comment by sekoenig** [comment]
Thanks for taking a look!

> The code looks good for me. However, there are some things we should consider:
> 
>     * are there any issues with older versions of HDF5 (1.12 is really bleeding edge stuff)

For the H5I_REFERENCE, I don't think so.  H5I_REFERENCE was marked as deprecated in 1.10.2, and subsequently removed.  I found
```
- Remove H5I_REFERENCE from the library

This ID class was never used by the library and has been removed.
```
here: https://fossies.org/linux/hdf5/release_docs/HISTORY-1_10_0-1_12_0.txt
> 
>     * will ObjectId still serve its purpose?
> 
>     * how are we identifying an object uniquely in an HDF5 file without its address as the mere path does not work?

That is a good point, there should be a better way to deal with this.  I will look into it.

**Comment by eugenwintersberger** [comment]
Thanks. This is really a nasty problem we definitely need a solution for this.

**Comment by sekoenig** [comment]
Okay, it seems like the correct solution for the ObjectId issue is to use H5O_info1_t and H5Oget_info1(), which give the old behavior.
I tracked down these were introduced in HDF 1.10.3, so I added appropriate `#if` switches. I have updated the pull request accordingly.

There are two separate commits for this, one that implements it for `object_id.hpp/cpp` (where the actual type is exposed in the interface unfortunately), and one for purely internal changes in `attribute_manager.cpp` and `node.cpp`.

**Comment by sekoenig** [comment]
Okay, there was one more twist:
- In HDF5 1.10.3 the "1" suffix was introduced for the function `H5Oget_info`, but not yet for the type `H50_info_t`.
- HDF5 1.12.0 then added the suffix for the type also.

I wish they were just keeping the interface stable...  Anyway, I updated the pull request once more.  It is now tested to compile with both 1.12.0 and 1.10.5.

**Pull request merged**
