### PR TITLE
Test cmake install and build examples

### PR DESCRIPTION
**Pull request by planetmarshall**
Adds a step to the Debian-10 github workflow to install the CMake project and test that the examples can be built. A few fixes were necessary to get this to work.

* Removed the `complex_io.cpp` example as it failed to build with what looked like a non-trivial linking error, though someone with more familiarity with the code may be able to fix it.

* Resolved some clang warnings by removing deprecated usages (usually unecessary declarations of default copy constructors - see https://clang.llvm.org/docs/DiagnosticsReference.html#wdeprecated-copy)

* Added github workflow badge to Readme

### CODE REVIEW

**Review by jkotan — CHANGES_REQUESTED** [review]
I don't think it is good idea to remove `complex_io.cpp`.
It would be much better to fix it by adding

`#include <h5cpp/contrib/stl/stl.hpp>`

to the file. See [pr_578](https://github.com/ess-dmsc/h5cpp/runs/4991778422?check_suite_focus=true). 
After #566 one needs to include  the `contrib`  `TypeTraits` definitions explicitly.
It would be good also to fix` the `TypeTraits<Image>.get()` i.e.
```patch
--- a/examples/image_h5.hpp
+++ b/examples/image_h5.hpp
@@ -72,6 +72,7 @@ class TypeTrait<Image<PixelT>>
     {
       const static DataspaceType & cref_ = Simple(hdf5::Dimensions{value.ny(),value.nx()},
                                                  hdf5::Dimensions{value.ny(),value.nx()});
+      return cref_;
     }
 
     static void *ptr(Image<PixelT> &value)

```

**Comment by planetmarshall** [comment]
Also added option to build the examples in the main CMake file (`H5CPP_BUILD_EXAMPLES`) as this makes it a bit easier to work with the example code as a developer.

**Comment by planetmarshall** [comment]
Incidentally, I *think* that's the codebase warning-free now so may be worth adding an option (say `H5CPP_COMPILE_STRICT`) and have it build with warnings as errors on CI.

**Review by jkotan — APPROVED** [review]
Looks good to me

**Comment by jkotan** [comment]
> Incidentally, I _think_ that's the codebase warning-free now so may be worth adding an option (say `H5CPP_COMPILE_STRICT`) and have it build with warnings as errors on CI.

It sounds good. But then probably the macos tests fail because
```
ld: warning: object file (/Users/runner/.conan/data/zlib/1.2.11/_/_/package/647afeb69d3b0a2d3d316e80b24d38c714cc6900/lib/libz.a(compress.o)) was built for newer macOS version (11.0) than being linked (10.15)
...

/Applications/Xcode_12.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: lib/libh5cpp.a(direct_driver.cpp.o) has no symbols
```

**Comment by planetmarshall** [comment]
> > Incidentally, I _think_ that's the codebase warning-free now so may be worth adding an option (say `H5CPP_COMPILE_STRICT`) and have it build with warnings as errors on CI.
> 
> It sounds good. But then probably the macos tests fail because
> 
> ```
> ld: warning: object file (/Users/runner/.conan/data/zlib/1.2.11/_/_/package/647afeb69d3b0a2d3d316e80b24d38c714cc6900/lib/libz.a(compress.o)) was built for newer macOS version (11.0) than being linked (10.15)
> ...
> 
> /Applications/Xcode_12.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: lib/libh5cpp.a(direct_driver.cpp.o) has no symbols
> ```

Yes, that *might* be OK because it's a link not a compilation warning. I'll test it and raise a separate PR if it works.

**Pull request merged**
