### PR TITLE
Issue 506

### PR DESCRIPTION
**Pull request by eugenwintersberger**
The tests should run. Can anyone may have a look on the Jenkins setup. Somehow I am too stupid to get a new container running.

### CODE REVIEW

**Comment by jkotan** [comment]
Your `conanfile_1.12.0.txt` should look like `conanfile_ess.txt`  (used for deb10) with replaced hdf5/1.10.6 by hdf5/1.12.0 .
Then it works.

**Comment by jkotan** [comment]
I've just updated the conanfile in your PR.

**Review by jkotan — APPROVED** [review]
Now it looks good to me.

**Comment by eugenwintersberger** [comment]
Ah. Thanks a lot. I will do the merge.

**Pull request merged**
