### PR TITLE
Issue 456: add retrieving a copy of the file image and loading an image file

### PR DESCRIPTION
**Pull request by jkotan**
Hi Eugen,

I've added proposal of the API  discussed in #456 i.e. 
```c++
  //!
  //! \brief retrieve a copy of the image of an existing, open file
  //!
  //! \throws std::runtime_error in case of a failure
  //! \tparam T source type
  //! \param data reference to the source instance of T
  //! \return size of used space in a buffer
  //! \sa ImageFlags
  //!
  template<typename T>
  size_t File::to_buffer(T &data) const;
```
and 

```c++
//! \brief load an image file from a buffer
//!
//! \throws std::runtime_error in case of a failure
//! \tparam T source type
//! \param data reference to the source instance of T
//! \param flags file image flags
//! \return a new File instance
//! \sa ImageFlags
//!
template<typename T>
DLL_EXPORT File from_buffer(T &data,
                            ImageFlags flags = ImageFlags::READONLY);
template<typename T>
DLL_EXPORT File from_buffer(T &data,
                            ImageFlagsBase flags);

```
An example of the implementation is attached in PR. Let me know your comments. If you agree on API I will add tests.

### CODE REVIEW

**Comment by jkotan** [comment]
I had to remove `const` from  the data parameter of `from_buffer()` because it may be not read-only.

I've added tests. The `test_image_from_buffer'  of `from_buffer()` function works OK.
However, tests with the `to_buffer()` method fail. i.e. it looks like from calling `File::to_buffer()` I get a corrupted HDF5 file.

**Comment by jkotan** [comment]
It looks like a `flush()` call was missing in `to_buffer` method. Now it works

**Comment by jkotan** [comment]
In HDF5 documentaion it is written that a buffer size can be different than the size file  returned by `File::size()` so I've added `File::buffer_size()`

**Review by eugenwintersberger — APPROVED** [review]
Looks so far good to me. I like the free standing functions ;). Go ahead and merge this.

**Pull request merged**
