### PR TITLE
Fix problem with static member variable

### LINKED ISSUE #363: Bug related to how C++ libraries deals with static member variables
Due to the way that C++ handles static member variables they must be set in an implementation file (*.cpp), not in a header file, to ensure that they are always available.

### PR DESCRIPTION
**Pull request by SkyToGround**
The code should be pretty self explanatory.

Closes #363

### CODE REVIEW

**Comment by eugenwintersberger** [comment]
Can you please fix the test issues. Afterwards I will happily approve this pull request ;)

**Comment by SkyToGround** [comment]
@eugenwintersberger There are not actually any test issues caused by this pull request. Instead, there is some problem with Jenkins that is causing all pull-request merge builds to fail. I can ask Afonso about it when I see him tomorrow.

**Comment by martukas** [comment]
Is this free of static variable initialization order problems? Just making sure.

**Comment by SkyToGround** [comment]
@martukas Depends on how you use it. Regardless, if you want to keep it as a static variable and make it possible to use it from anywhere else, this is what you have to do.

**Pull request merged**
