### PR TITLE
Issue 346

### PR DESCRIPTION
**Pull request by jkotan**
It resolves the problem of failing the STRONG close degree mode. 

To this end one has to close all `File` `hid_t`  created in `Link`s of  all `ObjectHandle`.

### CODE REVIEW

**Comment by jkotan** [comment]
Hi @martukas, I've simplified the tests by moving the common part in to `SetUp()`. The tests are based on idea that you can reopen the file in a different mode only if it is closed. With the `DegreeClose::STRONG` property closing the file should close also all children. 

However, the HDF5 library assumes that only one copy of file identifier is created when you open the file ones. In the current implementation of  `h5cpp` they are created hidden copies of file identifier in `Node::link_.parent_file_`. So since it were created by `h5cpp` in hidden way they have to be close by `h5cpp` in hidden way by `File::close()` in the STRONG mode.

**Comment by jkotan** [comment]
what about this PR?

**Comment by jkotan** [comment]
@eugenwintersberger , @martukas Is it something wrong with it? I thought it goes to 0.0.9.  DESY needs this feature.

**Comment by jkotan** [comment]
I've have seen the Eugen comments here.

**Comment by martukas** [comment]
Well, I approve it for what it's worth. Sorry for rushing the release. It was already way overdue.
For the next one, we should haver #352 in place, so lets not merge anything until that is done.

**Pull request merged**
