### PR TITLE
Issue 434: add access for missing datatype properties and float16_t type

### LINKED ISSUE #434: Half-precision float support?
I intend to use the Half precision floating-point format for storing data that do not need as much precision in order to save space. So does this code support half-precision float storage?

### PR DESCRIPTION
**Pull request by jkotan**
It resolves #434 by adding float16_t type and  missing datatype properties i.e.
- Integer -  precision, offset, order, pad
- Float -  precision, offset, order, pad, inpad, norm, ebias, fields

The properties `precision` and `offset` are very useful for NBit filter whille `fields` and `ebias` are used in creating of a new type examples i.e. `float16_t`.

### CODE REVIEW

**Review by yuelongyu — COMMENTED** [review]
the new implemented methods in integer.hpp, is that needed for half-precision float or it's for other purpose?

**Comment by jkotan** [comment]
> the new implemented methods in integer.hpp, is that needed for half-precision float or it's for other purpose?

It is just to provide a complete set of methods to create a new data types.

**Comment by jkotan** [comment]
> the new implemented methods in integer.hpp, is that needed for half-precision float or it's for other purpose?

But it is useful for the NBit filter

**Review by yuelongyu — APPROVED** [review]
looks good to me

**Pull request merged**
