### PR TITLE
Add traits for std::complex types

### LINKED ISSUE #452: std::complex datatype
I would like to add support for an std::complex<double> datatype.  I assume the best way to proceed with that would be to use the existing Compound class and add an approriate `class TypeTrait<std::complex<double>>`.  What exactly should go into that class, and what else would I need to define in addition?

### PR DESCRIPTION
**Pull request by sekoenig**
Resolves #452 .

### CODE REVIEW

**Review by eugenwintersberger — APPROVED** [review]
Looks all good to me. I guess I do the separation of the STL support code into a different directory by myself once I am done with moving the testing framework to CATCH2.

**Comment by eugenwintersberger** [comment]
Go a head with the merge and do not forget to close the ticket.

**Comment by sekoenig** [comment]
> Go a head with the merge and do not forget to close the ticket.

Thanks!  I will merge this in a moment.

**Comment by sekoenig** [comment]
> Looks all good to me. I guess I do the separation of the STL support code into a different directory by myself once I am done with moving the testing framework to CATCH2.

Please consider leaving it by default in `type_traits.hpp` unless you see a clear problem with it.  I really think complex numbers deserve this kind of status, while exotic types surely would be better placed in a separate place.

**Comment by sekoenig** [comment]
Okay, I don't have write access.  Can you just go ahead and merge?

**Pull request merged**
