### PR TITLE
fix datatype

### LINKED ISSUE #309: cannot read string attribute with array size 1
Hi,

I've encountered a problem that the h5cpp (v0.0.7) is no able to read string attribute which has array size 1. But if the array size shows as scalar, it works. 

>HDF5-DIAG: Error detected in HDF5 (1.10.0-patch1) thread 140552714533760:
  #000: ../../../src/H5A.c line 695 in H5Aread(): unable to read attribute
    major: Attribute
    minor: Read failed
  #001: ../../../src/H5Aint.c line 544 in H5A__read(): datatype conversion failed
    major: Attribute
    minor: Unable to encode value
  #002: ../../../src/H5T.c line 4844 in H5T_convert(): data type conversion failed
    major: Attribute
    minor: Unable to encode value
  #003: ../../../src/H5Tconv.c line 3193 in H5T__conv_vlen(): unable to convert between src and dest datatypes
    major: Datatype
    minor: Feature is unsupported
  #004: ../../../src/H5T.c line 4560 in H5T_path_find(): no appropriate function for conversion path
    major: Datatype
    minor: Unable to initialize object
terminate called after throwing an instance of 'std::runtime_error'

```C++
std::string base_class;
file.root().attributes["NX_class"].read(base_class); //works, the array size is scalar
std::cout<<base_class<<std::endl;

std::string testattr; 
file.root().attributes["testattr"].read(testattr); // doesn't work, the array size is 1
std::cout<<testattr<<std::endl;
```
testfile

### PR DESCRIPTION
**Pull request by jkotan**
it should fix #309

### CODE REVIEW

**Comment by jkotan** [comment]
That something I do not understand why you take a type of  what you read from an output buffer instead of the read variable.  In the output string buffer there is not written  if it is the SCALAR string or the SIMPLE string. You have to get this information from Attribute:: datatype(). If you dont do it during reading SIMPLE strings it crashes at https://github.com/jkotan/h5cpp/blob/master/src/h5cpp/attribute/attribute.hpp#L281 (https://github.com/ess-dmsc/h5cpp/issues/309).

**Comment by jkotan** [comment]
Here, there is an example of the test which causes  problems (`'std::bad_alloc'`) without this PR. In principle it could be added to the test suite. 

    #include <h5cpp/hdf5.hpp>
    #include <iostream>
    #include <string>


    int main()
    {
      auto file = hdf5::file::create("test.h5");
      auto r = file.root();
      std::string data = "hello";

      hdf5::datatype::String fixed_type = hdf5::datatype::String::fixed(20);
      hdf5::datatype::String var_type = hdf5::datatype::String::variable();

      auto a = r.attributes.create("scalar20", fixed_type, hdf5::dataspace::Scalar());
      a.write(data, fixed_type);
      std::string buffer;
      a.read(buffer); // causes terminate called after throwing an instance of 'std::bad_alloc'
      a.read(buffer, a.datatype());
      std::cout << buffer << std::endl;

      auto a2 = r.attributes.create("scalarvar", var_type, hdf5::dataspace::Scalar());
      a2.write(data, var_type);
      std::string buffer2;
      a2.read(buffer2);
      a2.read(buffer2, a2.datatype());
      std::cout << buffer2 << std::endl;

      auto a3 = r.attributes.create("simplevar", var_type, hdf5::dataspace::Simple({1}));
      a3.write(data, var_type);
      std::string buffer3;
      a3.read(buffer3);
      a3.read(buffer3, a3.datatype());
      std::cout << buffer3 << std::endl;

      auto a4 = r.attributes.create("simple20", fixed_type, hdf5::dataspace::Simple({1}));
      a4.write(data, fixed_type);
      std::string buffer4;
      a4.read(buffer4); // causes terminate called after throwing an instance of 'std::bad_alloc'
      a4.read(buffer4, a4.datatype());
      std::cout << buffer4 << std::endl;

      file.close();
      return 0;
    }

@eugenwintersberger, could you please provide a test which is broken by this PR?

**Comment by eugenwintersberger** [comment]
Ok. I guess I see your Problem. First things first: basically every IO operation in HDF5 requires two datatype. One for the data in memory and one for the data on disk. In the case of attributes we only need a type for the data in memory. The datatypes are required in order to perform an eventual type conversion. 

The Problem in your example above is a technical one with strings we have not solved yet in a rather simple to handle way. As you may have noticed we are using type traits to obtain the data type for a given C++ type. For `std::string` this is always a variable length string (which is what `std::string` is). 
There is no conversion from fixe to variable length strings and back. 
So in your code 

```cpp
//your attribute uses a fixed type
auto a = r.attributes.create("scalar20", fixed_type, hdf5::dataspace::Scalar());
a.write(data, fixed_type); //you force the method to use a fixed type for memory 
                                        //representation (which is ok)
std::string buffer;
a.read(buffer);   //here the automatism would choose a variable length type as a memory 
                          //representation for the buffer. Which is wrong and this is why the method fails
a.read(buffer, a.datatype()); // again you are choosing the right type but that's a decision that
                                            // the user should make
std::cout << buffer << std::endl;
```

**Comment by jkotan** [comment]
If `a.read(buffer)` is wrong then why it exists?  So you mean API is wrong (but implementation cannot be more important than API).

In my opinion the attribute object `a` has enough  information to read fixed size string  and cast it into `std::string` with the `read(buffer)` method.

BTW, In #309 there is also a problem to read variable length strings created by old `libpniio`.

**Comment by jkotan** [comment]
Also PR fix, i.e.

    a5.read(buffer5, a5.datatype());

works for multi-dim attributes

      auto a5 = r.attributes.create("simple20x", fixed_type, hdf5::dataspace::Simple({4}));
      a5.write(vec_data, fixed_type);
      std::vector<std::string> buffer5(4);
      // a5.read(buffer5); // causes terminate called after throwing an instance of 'std::bad_alloc'
      a5.read(buffer5, a5.datatype());
      std::cout << buffer5[0] << " " << buffer5[1] << " "
		<< buffer5[2] << " " << buffer5[3] << " " << std::endl;
      
      auto floattype = hdf5::datatype::create<float>();
      auto f6 = r.attributes.create("float", floattype, hdf5::dataspace::Simple({4}));
      f6.write(fvec_data, floattype);
      std::vector<float> buffer6(4);
      f6.read(buffer6);
      f6.read(buffer6, f6.datatype());
      std::cout << buffer6[0] << " " << buffer6[1] << " "
		<< buffer6[2] << " " << buffer6[3] << " " << std::endl;

For me it is natural that contrary to `Attribute::write(...)` the method Attribute::read(...) takes type from the data on disk. This information is only there. I don't understand why your code before PR should work.

**Comment by jkotan** [comment]
BTW, it is allowed to create PR for h5cpp from own fork? It looks like there are not tested on: https://jenkins.esss.dk/dm/job/ess-dmsc/job/h5cpp/view/default/

**Comment by jkotan** [comment]
moved to #316 and #315

**Pull request closed without merging**
