### PR TITLE
Version bump 0.6.1

### PR DESCRIPTION
**Pull request by ggoneiESS**
This branch corrects the version numbers in preparation and ensures all commits since 0.6.0 released are included, ready for 0.6.1.

### CODE REVIEW

**Comment by jkotan** [comment]
I understand it resolves #651

**Comment by ggoneiESS** [comment]
Correct, this is the main motivator for this version update - 0.6.1 also includes updates to various packages for Conan and fixes some conformity issues for compilation.

**Review by jkotan — APPROVED** [review]
It looks ok. Thanks.  Next week I will create deb packages and add new doc branch

**Comment by ggoneiESS** [comment]
So shall I leave you to do that on this branch and then create the release after merging?

**Comment by jkotan** [comment]
Please  go ahead with merging and taking. I will do it independently

**Pull request merged**
